### ISSUE TITLE
message page does not open

### ISSUE THREAD

**Issue by Cevocey** [RivaanRanawat/flutter-whatsapp-clone#13]
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building Builder(dirty):
type 'Null' is not a subtype of type 'bool'

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///C:/flutter-whatsapp-clone-master/lib/main.dart:31:12
When the exception was thrown, this was the stack: 
#0      generateRoute.<anonymous closure> (package:whatsapp_ui/router.dart:46:24)
#1      MaterialPageRoute.buildContent (package:flutter/src/material/page.dart:53:55)
#2      MaterialRouteTransitionMixin.buildPage (package:flutter/src/material/page.dart:111:27)
#3      _ModalScopeState.build.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/routes.dart:948:53)
#4      Builder.build (package:flutter/src/widgets/basic.dart:7448:48)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:5038:49)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (205 frames)
#214    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#215    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#216    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#217    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6041:32)
#218    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#221    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#222    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#223    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#226    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#227    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#228    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#229    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#230    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#231    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#232    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#233    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#234    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#235    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#236    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#237    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#238    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#239    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#240    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#241    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#242    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#243    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#245    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#246    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#247    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#248    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#249    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#250    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#251    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#252    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#253    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#254    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#255    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#256    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#257    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#258    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#259    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#260    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#261    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#262    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#263    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#264    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#265    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#266    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#267    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#268    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#269    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#270    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#271    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#272    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#273    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#274    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#275    _invoke (dart:ui/hooks.dart:145:13)
#276    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#277    _drawFrame (dart:ui/hooks.dart:112:31)
====================================================================================================

i got this error when opening message page

**Comment by Cevocey** [comment]
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building Builder(dirty):
type 'Null' is not a subtype of type 'String'

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///C:/flutter-whatsapp-clone-master/lib/main.dart:30:12
When the exception was thrown, this was the stack: 
#0      generateRoute.<anonymous closure> (package:whatsapp_ui/router.dart:46:23)
#1      MaterialPageRoute.buildContent (package:flutter/src/material/page.dart:53:55)
#2      MaterialRouteTransitionMixin.buildPage (package:flutter/src/material/page.dart:111:27)
#3      _ModalScopeState.build.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/routes.dart:948:53)
#4      Builder.build (package:flutter/src/widgets/basic.dart:7448:48)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:5038:49)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (205 frames)
#214    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#215    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#216    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#217    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6041:32)
#218    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#221    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#222    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#223    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#226    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#227    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#228    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#229    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#230    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#231    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#232    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#233    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#234    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#235    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#236    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#237    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#238    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#239    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#240    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#241    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#242    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#243    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#245    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#246    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#247    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#248    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#249    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#250    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#251    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#252    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#253    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#254    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#255    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#256    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#257    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#258    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#259    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#260    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#261    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#262    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#263    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#264    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#265    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#266    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#267    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#268    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#269    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#270    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#271    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#272    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#273    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#274    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#275    _invoke (dart:ui/hooks.dart:145:13)
#276    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#277    _drawFrame (dart:ui/hooks.dart:112:31)
====================================================================================================


and now i am getting this error instead of that previous error

**Comment by Cevocey** [comment]
i got it done

**Comment by IEarari** [comment]
@Cevocey How did you solve it ?
