### ISSUE TITLE
login fail 

### ISSUE THREAD

**Issue by developer-rahim** [RivaanRanawat/flutter-whatsapp-clone#16]
E/FirebaseAuth( 7188): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17093 null
E/flutter ( 7188): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.
E/flutter ( 7188): #0      AuthRepository.signInWithPhone.<anonymous closure>
auth_repository.dart:48
E/flutter ( 7188): #1      MethodChannelFirebaseAuth.verifyPhoneNumber.<anonymous closure>
method_channel_firebase_auth.dart:622
E/flutter ( 7188): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 7188): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 7188): #4      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter ( 7188): #5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter ( 7188): #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter ( 7188): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 7188): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 7188):

**Comment by rakeshchandrapal** [comment]
Did you connect the app with the firebase ?

**Comment by rakeshchandrapal** [comment]
> E/FirebaseAuth( 7188): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17093 null E/flutter ( 7188): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details. E/flutter ( 7188): #0 AuthRepository.signInWithPhone. auth_repository.dart:48 E/flutter ( 7188): #1 MethodChannelFirebaseAuth.verifyPhoneNumber. method_channel_firebase_auth.dart:622 E/flutter ( 7188): #2 _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10) E/flutter ( 7188): #3 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11) E/flutter ( 7188): #4 _DelayedData.perform (dart:async/stream_impl.dart:515:14) E/flutter ( 7188): #5 _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11) E/flutter ( 7188): #6 _PendingEvents.schedule. (dart:async/stream_impl.dart:591:7) E/flutter ( 7188): #7 _microtaskLoop (dart:async/schedule_microtask.dart:40:21) E/flutter ( 7188): #8 _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5) E/flutter ( 7188):


Did you connect the app with the firebase ?
